spring:
    h2:
      console:
        enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
        path: /h2
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        dirver-class-name: org.h2.Driver
    
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    
    message:
        basename: messages,errors

logging:
    level:
        org.hibernate.SQL: debug

# server:
#     servlet:
#         session:
#             tracking-modes: cookie
#             timeout: 60
